---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages 
    package:
      name:
        - tmux
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/ansible-wallpaper.png
      dest: /usr/share/backgrounds/ansible-wallpaper.png
      owner: root
      group: root

  - name: set wallpaper
    become_user: lijun
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

  - name: set wallpaper position
    become_user: lijun
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: Set lock screen background
    become_user: lijun
    dconf: 
      key: "/org/gnome/desktop/screensaver/picture-uri" 
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

